### PR TITLE
Fixed Unicode regex pattern and conversion

### PR DESCRIPTION
**Pull request by vegardan**
The Unicode regex pattern would sometimes split emojis which made them break.
The emojiToUnicode() function always returned the wrong value when converting emojis with 1 codepoint consisting of 4 characters. For example \u2708 (airplane) was converted to 9992 (invalid).

### CODE REVIEW

**Comment by bigblackclock** [comment]
thank you for the PR, will review it ASAP

**Comment by bigblackclock** [comment]
Hey, 
some emojis still not working for example "☺️",
could you please check the list https://getemoji.com/

**Comment by vegardan** [comment]
I checked it out and the emoji you sent "Smiling Face" has two codepoints. U+263A and U+FE0F, but the last codepoint is just a variation selector that is no longer used for this emoji. Please use this list instead for the latest unicode emoji list: https://unicode.org/emoji/charts/full-emoji-list.html
Android natively only uses the first codepoint and I already tested all emojis on the emoji keyboard including different variations such as skin tone.

**Comment by hadi-codes** [comment]
Hey, I did update the emoji regex to the same regex from your PR.
For the EmojiToUnicode method, I used Twitter [implementation](https://github.com/twitter/twemoji/blob/master/scripts/build.js) 
Thank You :)

**Pull request closed without merging**
